### ISSUE TITLE
ValueError: Cannot feed value of shape (0,) for Tensor 'input_images:0', which has shape '(64, 128, 128, 3)'

### ISSUE THREAD

**Issue by airalcorn2** [lmb-freiburg/mv3d#7]
When I run:

```bash
python3 nobg_nodm.py
```

in test mode, I get the following error:

```
loading test set...
done.
WARNING:tensorflow:From nobg_nodm.py:86 in buildModel.: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
loading snapshots/nobg_nodm/snapshot435000-435000...
done.
Traceback (most recent call last):
  File "nobg_nodm.py", line 186, in <module>
    net.test(0)
  File "nobg_nodm.py", line 120, in test
    self.labels: batch_labels})
  File "/home/michael/.pyenv/versions/3.6.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/home/michael/.pyenv/versions/3.6.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 943, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (0,) for Tensor 'input_images:0', which has shape '(64, 128, 128, 3)'
```

Seems like it's probably related to [this](https://github.com/lmb-freiburg/mv3d/issues/1). I'll see if I can figure it out.

**Comment by airalcorn2** [comment]
Yes, if you add:

```python
print(path)
```

to `load_test_set` in `tf_utils.py` it prints:

`/home/michael/mv3d/../data`

Changing:

```python
path = os.path.join(script_path, '../data')
```

to:

```python
path = os.path.join(script_path, 'data')
```

makes it past this error.
